---

name: Kubectl
on: [push, pull_request]
jobs:
  kubectl:
    name: version
    runs-on: macos
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: victorsalaun/gh-actions/kubectl@master
        with:
          subcommand: version --client
